/crazyflie_server:
  ros__parameters:
    use_sim_time: true
  # Gazebo simulation
    sim:
      max_dt: 0
      backend: gazebo
      visualizations:
        rviz:
          enabled: true
        pdf:
          enabled: false
          output_file: "result.pdf"
      controller: mellinger